---
- include: service_state.yaml operation=stopped
- hosts: hostList
  tasks:
    - name: Swap off
      shell: swapoff /swapfile
      become: yes
    - name: Remove /swapfile
      shell: rm -rf /swapfile
      become: yes

