---
- hosts: hostList
  vars_files:
    - vars/cinder_info.yml
  tasks:
    - name: Add volume vip host
      lineinfile: dest=/etc/hosts line="{{keepalived_haproxy_vip}} {{vol_vip_host}}" state=present
      become: yes
    - name: Copy cinder conf
      template: src=src/cinder.conf dest=/etc/cinder/cinder.conf
      become: yes
    - name: Update api-paste.ini
      template: src=src/api-paste.ini dest=/etc/cinder/api-paste.ini
      become: yes
    - name: Make ceph dir
      file: path=/etc/ceph state=directory mode=0755
      become: yes
    - name: Copy ceph conf
      template: src=src/ceph.conf dest=/etc/ceph/
      become: yes

