---
- hosts: admin
  vars_files:
    - vars/ceph_info.yml
  tasks:
    - name: Install ceph on ceph nodes
      command: ceph-deploy --overwrite-conf install {{item.hostname}}
      with_items: "{{mons + osds}}"

